plotSignatures(Sig6, sub = 'MB-REC-06')
Sig10 <- whichSignatures(tumor.ref = Sigs_input_final, sample.id = "MB-REC-10", contexts.needed = "TRUE")
plotSignatures(Sig10, sub = 'MB-REC-10')
Sig41 <- whichSignatures(tumor.ref = Sigs_input_final, sample.id = "MB-REC-41", contexts.needed = "TRUE")
plotSignatures(Sig41, sub = 'MB-REC-41')
Sig09 <- whichSignatures(tumor.ref = Sigs_input_final, sample.id = "MB-REC-09", contexts.needed = "TRUE")
plotSignatures(Sig09, sub = 'MB-REC-09')
Sig02 <- whichSignatures(tumor.ref = Sigs_input_final, sample.id = "MB-REC-02", contexts.needed = "TRUE")
plotSignatures(Sig02, sub = 'MB-REC-02')
Sig03 <- whichSignatures(tumor.ref = Sigs_input_final, sample.id = "MB-REC-03", contexts.needed = "TRUE")
plotSignatures(Sig03, sub = 'MB-REC-03')
